/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * user defined build metrics from `$out/nix-support/hydra-metrics`. The file should define metrics separated by new lines using the following format:  ``` <name> <value>[ <unit>] ``` The name and unit fields are strings, the value is a float. The unit is optional. 
 *
 * @export
 * @interface BuildBuildmetrics
 */
export interface BuildBuildmetrics {

    /**
     * name of the measured build metric
     *
     * @type {string}
     * @memberof BuildBuildmetrics
     */
    name?: string;

    /**
     * measured value
     *
     * @type {string}
     * @memberof BuildBuildmetrics
     */
    value?: string;

    /**
     * unit of the measured build metric
     *
     * @type {string}
     * @memberof BuildBuildmetrics
     */
    unit?: string;
}
