/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse200
 */
export interface InlineResponse200 {

    /**
     * user
     *
     * @type {string}
     * @memberof InlineResponse200
     */
    username?: string;

    /**
     * full name
     *
     * @type {string}
     * @memberof InlineResponse200
     */
    fullname?: string;

    /**
     * email
     *
     * @type {string}
     * @memberof InlineResponse200
     */
    emailaddress?: string;

    /**
     * user roles
     *
     * @type {Array<string>}
     * @memberof InlineResponse200
     */
    userroles?: Array<string>;
}
