/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {

    /**
     * URL of the created project
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    uri?: string;

    /**
     * name of the project
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    name?: string;

    /**
     * URL of the created project
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    redirect?: string;

    /**
     * type of the created resource (\"project\")
     *
     * @type {string}
     * @memberof InlineResponse201
     */
    type?: string;
}
