/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2003
 */
export interface InlineResponse2003 {

    /**
     * root of the Hydra instance
     *
     * @type {string}
     * @memberof InlineResponse2003
     */
    redirect?: string;
}
