/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface JobsetOverviewInner
 */
export interface JobsetOverviewInner {

    /**
     * name of the jobset
     *
     * @type {string}
     * @memberof JobsetOverviewInner
     */
    name?: string;

    /**
     * name of the project
     *
     * @type {string}
     * @memberof JobsetOverviewInner
     */
    project?: string;

    /**
     * number of evaluations
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    nrtotal?: number;

    /**
     * interval in seconds at which to check the jobset inputs
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    checkinterval?: number;

    /**
     * true if the evaluation had errors
     *
     * @type {boolean}
     * @memberof JobsetOverviewInner
     */
    haserrormsg?: boolean;

    /**
     * number of scheduled evaluations
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    nrscheduled?: number;

    /**
     * number of failed evaluations
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    nrfailed?: number;

    /**
     * time an error occurred during evaluation (unix time stamp)
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    errortime?: number;

    /**
     * contains the error message when there was a problem fetching sources for a jobset
     *
     * @type {any}
     * @memberof JobsetOverviewInner
     */
    fetcherrormsg?: any | null;

    /**
     * time when build started
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    starttime?: number | null;

    /**
     * the last time the jobset inputs where checked to see if an evaluation needs to be scheduled (unix time stamp)
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    lastcheckedtime?: number;

    /**
     * time of the last evaluation trigger for this jobset (unix time stamp)
     *
     * @type {number}
     * @memberof JobsetOverviewInner
     */
    triggertime?: number | null;
}
