/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { BuildBuildmetrics } from './build-buildmetrics';
import { BuildOutput } from './build-output';
import { BuildProduct } from './build-product';
 /**
 * 
 *
 * @export
 * @interface Build
 */
export interface Build {

    /**
     * @type {number}
     * @memberof Build
     */
    id?: number;

    /**
     * time when build started
     *
     * @type {number}
     * @memberof Build
     */
    starttime?: number;

    /**
     * time when build ended
     *
     * @type {number}
     * @memberof Build
     */
    stoptime?: number;

    /**
     * time when the build was first created
     *
     * @type {number}
     * @memberof Build
     */
    timestamp?: number;

    /**
     * list of evaluations this build is part of
     *
     * @type {Array<number>}
     * @memberof Build
     */
    jobsetevals?: Array<number>;

    /**
     * true when the build is finished
     *
     * @type {boolean}
     * @memberof Build
     */
    finished?: boolean;

    /**
     * name from the build's derivation
     *
     * @type {string}
     * @memberof Build
     */
    nixname?: string;

    /**
     * Indicates the build status:</br> <ul>  <li>0 : succeeded</li>  <li>1 : failed</li>  <li>2 : dependency failed</li>  <li>3 : aborted</li>  <li>4 : canceled by the user</li>  <li>6 : failed with output</li>  <li>7 : timed out</li>  <li>9 : aborted</li>  <li>10 : log size limit exceeded</li>  <li>11 : output size limit exceeded</li>  <li>*  : failed</li> </ul> <strong>Note:</strong>buildstatus should only be `null` if `finished` is false. 
     *
     * @type {number}
     * @memberof Build
     */
    buildstatus?: number | null;

    /**
     * jobset this build belongs to
     *
     * @type {string}
     * @memberof Build
     */
    jobset?: string;

    /**
     * determines the priority with which this build will be executed (higher value means higher priority)
     *
     * @type {number}
     * @memberof Build
     */
    priority?: number;

    /**
     * nix attribute from the nixexprpath
     *
     * @type {string}
     * @memberof Build
     */
    job?: string;

    /**
     * filename of the drv
     *
     * @type {string}
     * @memberof Build
     */
    drvpath?: string;

    /**
     * system this build was done for
     *
     * @type {string}
     * @memberof Build
     */
    system?: string;

    /**
     * project this build belongs to
     *
     * @type {string}
     * @memberof Build
     */
    project?: string;

    /**
     * @type {{ [key: string]: BuildProduct; }}
     * @memberof Build
     */
    buildproducts?: { [key: string]: BuildProduct; };

    /**
     * @type {{ [key: string]: BuildOutput; }}
     * @memberof Build
     */
    buildoutputs?: { [key: string]: BuildOutput; };

    /**
     * @type {BuildBuildmetrics}
     * @memberof Build
     */
    buildmetrics?: BuildBuildmetrics;
}
