/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JobsetEval } from './jobset-eval';
 /**
 * 
 *
 * @export
 * @interface Evaluations
 */
export interface Evaluations {

    /**
     * first list of results
     *
     * @type {string}
     * @memberof Evaluations
     */
    first?: string;

    /**
     * next list of results
     *
     * @type {string}
     * @memberof Evaluations
     */
    next?: string;

    /**
     * last list of results
     *
     * @type {string}
     * @memberof Evaluations
     */
    last?: string;

    /**
     * List of evaluations
     *
     * @type {Array<{ [key: string]: JobsetEval; }>}
     * @memberof Evaluations
     */
    evals?: Array<{ [key: string]: JobsetEval; }>;
}
