/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2011
 */
export interface InlineResponse2011 {

    /**
     * url pointing to the webui for the created jobset
     *
     * @type {string}
     * @memberof InlineResponse2011
     */
    redirect?: string;

    /**
     * url to the created jobset
     *
     * @type {string}
     * @memberof InlineResponse2011
     */
    uri?: string;

    /**
     * name of the created jobset
     *
     * @type {string}
     * @memberof InlineResponse2011
     */
    name?: string;

    /**
     * Set to \"jobset\"
     *
     * @type {string}
     * @memberof InlineResponse2011
     */
    type?: string;
}
