/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {

    /**
     * url pointing to the webui for the created jobset
     *
     * @type {string}
     * @memberof InlineResponse2004
     */
    redirect?: string;
}
