/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface JobsetInput
 */
export interface JobsetInput {

    /**
     * name of the input
     *
     * @type {string}
     * @memberof JobsetInput
     */
    name?: string;

    /**
     * value of the input
     *
     * @type {string}
     * @memberof JobsetInput
     */
    value?: string;

    /**
     * type of input
     *
     * @type {string}
     * @memberof JobsetInput
     */
    type?: string;

    /**
     * whether or not to email responsible parties
     *
     * @type {boolean}
     * @memberof JobsetInput
     */
    emailresponsible?: boolean;
}
