/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { JobsetOverviewInner } from './jobset-overview-inner';
 /**
 * 
 *
 * @export
 * @interface JobsetOverview
 */
export interface JobsetOverview extends Array<JobsetOverviewInner> {
}
