/* tslint:disable */
/* eslint-disable */
/**
 * Hydra API
 * Specification of the Hydra REST API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { DeclarativeInput } from './declarative-input';
 /**
 * 
 *
 * @export
 * @interface Project
 */
export interface Project {

    /**
     * username of the project owner
     *
     * @type {string}
     * @memberof Project
     */
    owner?: string;

    /**
     * name of the project
     *
     * @type {string}
     * @memberof Project
     */
    name?: string;

    /**
     * name to be displayed in the web interface
     *
     * @type {string}
     * @memberof Project
     */
    displayname?: string;

    /**
     * description of the project
     *
     * @type {string}
     * @memberof Project
     */
    description?: string;

    /**
     * homepage of the project
     *
     * @type {string}
     * @memberof Project
     */
    homepage?: string;

    /**
     * when set to true the project is not displayed in the web interface
     *
     * @type {boolean}
     * @memberof Project
     */
    hidden?: boolean;

    /**
     * when set to true the project gets scheduled for evaluation
     *
     * @type {boolean}
     * @memberof Project
     */
    enabled?: boolean;

    /**
     * when true the project's jobsets support executing dynamically defined RunCommand hooks. Requires the server and project's configuration to also enable dynamic RunCommand.
     *
     * @type {boolean}
     * @memberof Project
     */
    enableDynamicRunCommand?: boolean;

    /**
     * @type {any}
     * @memberof Project
     */
    declarative?: any;

    /**
     * list of jobsets belonging to this project
     *
     * @type {Array<string>}
     * @memberof Project
     */
    jobsets?: Array<string>;
}
